### ISSUE TITLE
[4pts] Create a Public recipe list page (Member A)

### ISSUE THREAD

**Issue by EddyShimwa** [EddyShimwa/Recipe_app#1]
# Requirements
- Public recipe list:
   - Should display a list of all public recipes ordered by newest as in the wireframe.
   - Should lead to recipe details.

**Comment by PeteUgwu** [comment]
# Tasks
- [ ] Define the #index action in PublicRecipesController
- [ ] Select all recipes with public: true from the database
- [ ] Create a view to display the public recipes

**Comment by PeteUgwu** [comment]
# Wireframe

![Image](https://user-images.githubusercontent.com/47011876/234061969-81b42fec-7555-440d-b26f-37a8d39e0ca6.png)
