### ISSUE TITLE
[4pts] Create Recipes list (Member B)

### ISSUE THREAD

**Issue by EddyShimwa** [EddyShimwa/Recipe_app#2]
# Requirements
- Recipes list:
   - Should display a list of recipes created by the logged-in user as in the wireframe.
   - Should lead to recipe details.
   - If the user is the owner of the recipe, should allow the user to delete it.

**Comment by PeteUgwu** [comment]
# Tasks
- [ ] Create routes for Recipe
- [ ] Add actions in RecipesController
- [ ] Create a view for recipe#index

# Wireframe
![Image](https://user-images.githubusercontent.com/47011876/234059112-3bef7f74-20d4-489f-ba72-80e5238c1e6c.png)
