### ISSUE TITLE
[4pts] Create Food list (Member A)

### ISSUE THREAD

**Issue by EddyShimwa** [EddyShimwa/Recipe_app#8]
# Requirements

- Food list:
   - [ ] Should display a list of food added by the logged-in user as in the wireframe (for teams with only 2 people - display also quantity of a given food).
   - [ ] Should lead to a form that allows users to add new food.

**Comment by PeteUgwu** [comment]
# Tasks

- [ ] Create routes for Food
- [ ] Add actions in FoodsController
- [ ] Create a view for the food#index page

# Wireframe

![Image](https://user-images.githubusercontent.com/47011876/234060280-3fdb58fa-458d-4d63-bca3-6c68c2b5b892.png)
