### ISSUE TITLE
[4pts] Create Recipe details page (Member B)

### ISSUE THREAD

**Issue by EddyShimwa** [EddyShimwa/Recipe_app#9]
# Requirements
- Recipe details:

- [x]    - Should display a toggle button that allows for a recipe to be made public or private.
- [x]    - If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe.
- [x]    - If the user is the owner of the recipe, should lead to the form that allows the user to add new food.

**Comment by PeteUgwu** [comment]
# Tasks

 - [ ] Create a view to display a recipe
 - [ ] Create a toggle button
 - [ ] Create a form to add new food

**Comment by PeteUgwu** [comment]
# Wireframe

![Image](https://user-images.githubusercontent.com/47011876/234063478-501d22eb-bf81-424c-8f80-868ce22f9c47.png)
